### ISSUE TITLE
Option to disable generation of JSON methods for dependencies

### ISSUE THREAD

**Issue by jalaziz** [mfridman/protoc-gen-go-json#4] opened 2024-03-27 17:46 UTC
The latest version of the plugin (v1.3.0) seems to have introduced a change that causes marshaling and unmarshaling methods to be generated for protobuf dependencies (e.g. `google.api`, `google.protobuf`, etc).

This is not necessarily desirable and I'm not even sure it works (unless the dependencies are also compiled into the same directory).

**Comment by mfridman** [comment] 2024-03-27 17:57
Thanks for the report, I'll take a look and fix it up a bit later on.

**Comment by mfridman** [comment] 2024-03-27 23:08
Alright, this had a fairly simple fix. I pulled in a new library ([bufbuild/protoplugin](https://github.com/bufbuild/protoplugin)) and forgot to add a check.

https://github.com/mfridman/protoc-gen-go-json/commit/27a38c677f12d54624a7a03cc892b1c195de1b00

I'll follow up with a few test cases. But will publish a patch version to get folks unblocked, since it's a regression.

https://github.com/mfridman/protoc-gen-go-json/releases/tag/v1.3.1 should fix this.

**Comment by mfridman** [comment] 2024-04-03 12:35
Going to close this issue, as it should be fixed. But if you continue to have issues don't hesitate to let me know.

**Closed as completed by mfridman** 2024-04-03 12:35 UTC
